### ISSUE TITLE
 There are no commands defined in the "AngkorCMS" namespace.

### ISSUE THREAD

**Issue by skanel** [lucbu/AngkorCMS#1]
C:\wamp\www\AngkorCMS>php artisan AngkorCMS:install

  [InvalidArgumentException]
  There are no commands defined in the "AngkorCMS" namespace.

C:\wamp\www\AngkorCMS>

How to fix it?

**Comment by lucbu** [comment]
I can't try at home because I don't have laptop. The command "php artisan angkorcms:install" should work after the "composer install" and the customization of the .env file.

**Comment by skanel** [comment]
Yes , it works for me now,just php artisan angkorcms:install is difference php artisan AngkorCMS:install
