### ISSUE TITLE
Would like to see some demos?

### ISSUE THREAD

**Issue by skanel** [lucbu/AngkorCMS#2]
it it possible to show some demo products or screenshot?

**Comment by lucbu** [comment]
You can see demo and explanation about how the CMS works in the pdf files "AngkorCMS - Documentation.pdf"
![doc](https://cloud.githubusercontent.com/assets/5434555/8274316/8b07684c-18b9-11e5-9226-131409a0a0a9.PNG)

Also in the wiki.
