### ISSUE TITLE
Can't find this file

### ISSUE THREAD

**Issue by SaifulAzam** [lucbu/AngkorCMS#3]
FatalErrorException in ProviderRepository.php line 146:
Class 'AngkorCMS\Content\AngkorCMSContentServiceProvider' not found

"composer install"
Show this error:
 [InvalidArgumentException]  
  The "angkorcms\content" directory does not exist.

**Comment by lucbu** [comment]
Hello, did you try "composer dump-autoload" or "php artisan config:clear" ?
